name: voicerecorder_native
description: "Código nativo de la grabadora: conversión de audio y acceso a carpetas."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.13.5
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: es.germade.voicerecorder_native
        pluginClass: VoicerecorderNativePlugin
      ios:
        pluginClass: VoicerecorderNativePlugin
